INSERT INTO `students`(`name`, `status`, `role`, `password`, `email`, `image`, `room_number`, `date_naissance`, `ville`, `tel`, `filliere`, `annee_scolaire`, `genre`)
VALUES
  ('1-GM1', 'externe', 'student', NULL, '1-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('2-GM1', 'externe', 'student', NULL, '2-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('3-GM1', 'externe', 'student', NULL, '3-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('4-GM1', 'externe', 'student', NULL, '4-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('5-GM1', 'externe', 'student', NULL, '5-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('6-GM1', 'externe', 'student', NULL, '6-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('7-GM1', 'externe', 'student', NULL, '7-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('8-GM1', 'externe', 'student', NULL, '8-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('9-GM1', 'externe', 'student', NULL, '9-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('10-GM1', 'externe', 'student', NULL, '10-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('11-GM1', 'externe', 'student', NULL, '11-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('12-GM1', 'externe', 'student', NULL, '12-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('13-GM1', 'externe', 'student', NULL, '13-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('14-GM1', 'externe', 'student', NULL, '14-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('15-GM1', 'externe', 'student', NULL, '15-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('16-GM1', 'externe', 'student', NULL, '16-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('17-GM1', 'externe', 'student', NULL, '17-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('18-GM1', 'externe', 'student', NULL, '18-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('19-GM1', 'externe', 'student', NULL, '19-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('20-GM1', 'externe', 'student', NULL, '20-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('21-GM1', 'externe', 'student', NULL, '21-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('22-GM1', 'externe', 'student', NULL, '22-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('23-GM1', 'externe', 'student', NULL, '23-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('24-GM1', 'externe', 'student', NULL, '24-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('25-GM1', 'externe', 'student', NULL, '25-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('26-GM1', 'externe', 'student', NULL, '26-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('27-GM1', 'externe', 'student', NULL, '27-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('28-GM1', 'externe', 'student', NULL, '28-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('29-GM1', 'externe', 'student', NULL, '29-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('30-GM1', 'externe', 'student', NULL, '30-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('31-GM1', 'externe', 'student', NULL, '31-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('32-GM1', 'externe', 'student', NULL, '32-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('33-GM1', 'externe', 'student', NULL, '33-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('34-GM1', 'externe', 'student', NULL, '34-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('35-GM1', 'externe', 'student', NULL, '35-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('36-GM1', 'externe', 'student', NULL, '36-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('37-GM1', 'externe', 'student', NULL, '37-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('38-GM1', 'externe', 'student', NULL, '38-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('39-GM1', 'externe', 'student', NULL, '39-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('40-GM1', 'externe', 'student', NULL, '40-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('41-GM1', 'externe', 'student', NULL, '41-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('42-GM1', 'externe', 'student', NULL, '42-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('43-GM1', 'externe', 'student', NULL, '43-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('44-GM1', 'externe', 'student', NULL, '44-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('45-GM1', 'externe', 'student', NULL, '45-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('46-GM1', 'externe', 'student', NULL, '46-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('47-GM1', 'externe', 'student', NULL, '47-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('48-GM1', 'externe', 'student', NULL, '48-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
  ('49-GM1', 'externe', 'student', NULL, '49-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'boy'),
  ('50-GM1', 'externe', 'student', NULL, '50-GM1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '1', 'girl'),
--   GM2
  ('1-GM2', 'externe', 'student', NULL, '1-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('2-GM2', 'externe', 'student', NULL, '2-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('3-GM2', 'externe', 'student', NULL, '3-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('4-GM2', 'externe', 'student', NULL, '4-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('5-GM2', 'externe', 'student', NULL, '5-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('6-GM2', 'externe', 'student', NULL, '6-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('7-GM2', 'externe', 'student', NULL, '7-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('8-GM2', 'externe', 'student', NULL, '8-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('9-GM2', 'externe', 'student', NULL, '9-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('10-GM2', 'externe', 'student', NULL, '10-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('11-GM2', 'externe', 'student', NULL, '11-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('12-GM2', 'externe', 'student', NULL, '12-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('13-GM2', 'externe', 'student', NULL, '13-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('14-GM2', 'externe', 'student', NULL, '14-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('15-GM2', 'externe', 'student', NULL, '15-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('16-GM2', 'externe', 'student', NULL, '16-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('17-GM2', 'externe', 'student', NULL, '17-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('18-GM2', 'externe', 'student', NULL, '18-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('19-GM2', 'externe', 'student', NULL, '19-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('20-GM2', 'externe', 'student', NULL, '20-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('21-GM2', 'externe', 'student', NULL, '21-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('22-GM2', 'externe', 'student', NULL, '22-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('23-GM2', 'externe', 'student', NULL, '23-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('24-GM2', 'externe', 'student', NULL, '24-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('25-GM2', 'externe', 'student', NULL, '25-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('26-GM2', 'externe', 'student', NULL, '26-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('27-GM2', 'externe', 'student', NULL, '27-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('28-GM2', 'externe', 'student', NULL, '28-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('29-GM2', 'externe', 'student', NULL, '29-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('30-GM2', 'externe', 'student', NULL, '30-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('31-GM2', 'externe', 'student', NULL, '31-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('32-GM2', 'externe', 'student', NULL, '32-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('33-GM2', 'externe', 'student', NULL, '33-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('34-GM2', 'externe', 'student', NULL, '34-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('35-GM2', 'externe', 'student', NULL, '35-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('36-GM2', 'externe', 'student', NULL, '36-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('37-GM2', 'externe', 'student', NULL, '37-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('38-GM2', 'externe', 'student', NULL, '38-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('39-GM2', 'externe', 'student', NULL, '39-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('40-GM2', 'externe', 'student', NULL, '40-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('41-GM2', 'externe', 'student', NULL, '41-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('42-GM2', 'externe', 'student', NULL, '42-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('43-GM2', 'externe', 'student', NULL, '43-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('44-GM2', 'externe', 'student', NULL, '44-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('45-GM2', 'externe', 'student', NULL, '45-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('46-GM2', 'externe', 'student', NULL, '46-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('47-GM2', 'externe', 'student', NULL, '47-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('48-GM2', 'externe', 'student', NULL, '48-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
  ('49-GM2', 'externe', 'student', NULL, '49-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'boy'),
  ('50-GM2', 'externe', 'student', NULL, '50-GM2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GM)', '2', 'girl'),
--   GP1
  ('1-GP1', 'externe', 'student', NULL, '1-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('2-GP1', 'externe', 'student', NULL, '2-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('3-GP1', 'externe', 'student', NULL, '3-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('4-GP1', 'externe', 'student', NULL, '4-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('5-GP1', 'externe', 'student', NULL, '5-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('6-GP1', 'externe', 'student', NULL, '6-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('7-GP1', 'externe', 'student', NULL, '7-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('8-GP1', 'externe', 'student', NULL, '8-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('9-GP1', 'externe', 'student', NULL, '9-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('10-GP1', 'externe', 'student', NULL, '10-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('11-GP1', 'externe', 'student', NULL, '11-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('12-GP1', 'externe', 'student', NULL, '12-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('13-GP1', 'externe', 'student', NULL, '13-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('14-GP1', 'externe', 'student', NULL, '14-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('15-GP1', 'externe', 'student', NULL, '15-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('16-GP1', 'externe', 'student', NULL, '16-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('17-GP1', 'externe', 'student', NULL, '17-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('18-GP1', 'externe', 'student', NULL, '18-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('19-GP1', 'externe', 'student', NULL, '19-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('20-GP1', 'externe', 'student', NULL, '20-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('21-GP1', 'externe', 'student', NULL, '21-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('22-GP1', 'externe', 'student', NULL, '22-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('23-GP1', 'externe', 'student', NULL, '23-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('24-GP1', 'externe', 'student', NULL, '24-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('25-GP1', 'externe', 'student', NULL, '25-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('26-GP1', 'externe', 'student', NULL, '26-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('27-GP1', 'externe', 'student', NULL, '27-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('28-GP1', 'externe', 'student', NULL, '28-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('29-GP1', 'externe', 'student', NULL, '29-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('30-GP1', 'externe', 'student', NULL, '30-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('31-GP1', 'externe', 'student', NULL, '31-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('32-GP1', 'externe', 'student', NULL, '32-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('33-GP1', 'externe', 'student', NULL, '33-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('34-GP1', 'externe', 'student', NULL, '34-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('35-GP1', 'externe', 'student', NULL, '35-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('36-GP1', 'externe', 'student', NULL, '36-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('37-GP1', 'externe', 'student', NULL, '37-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('38-GP1', 'externe', 'student', NULL, '38-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('39-GP1', 'externe', 'student', NULL, '39-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('40-GP1', 'externe', 'student', NULL, '40-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('41-GP1', 'externe', 'student', NULL, '41-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('42-GP1', 'externe', 'student', NULL, '42-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('43-GP1', 'externe', 'student', NULL, '43-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('44-GP1', 'externe', 'student', NULL, '44-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('45-GP1', 'externe', 'student', NULL, '45-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('46-GP1', 'externe', 'student', NULL, '46-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('47-GP1', 'externe', 'student', NULL, '47-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('48-GP1', 'externe', 'student', NULL, '48-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
  ('49-GP1', 'externe', 'student', NULL, '49-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'boy'),
  ('50-GP1', 'externe', 'student', NULL, '50-GP1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie de procédé (GP)', '1', 'girl'),
--   GP2
  ('1-GP2', 'externe', 'student', NULL, '1-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('2-GP2', 'externe', 'student', NULL, '2-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('3-GP2', 'externe', 'student', NULL, '3-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('4-GP2', 'externe', 'student', NULL, '4-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('5-GP2', 'externe', 'student', NULL, '5-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('6-GP2', 'externe', 'student', NULL, '6-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('7-GP2', 'externe', 'student', NULL, '7-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('8-GP2', 'externe', 'student', NULL, '8-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('9-GP2', 'externe', 'student', NULL, '9-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('10-GP2', 'externe', 'student', NULL, '10-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('11-GP2', 'externe', 'student', NULL, '11-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('12-GP2', 'externe', 'student', NULL, '12-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('13-GP2', 'externe', 'student', NULL, '13-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('14-GP2', 'externe', 'student', NULL, '14-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('15-GP2', 'externe', 'student', NULL, '15-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('16-GP2', 'externe', 'student', NULL, '16-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('17-GP2', 'externe', 'student', NULL, '17-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('18-GP2', 'externe', 'student', NULL, '18-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('19-GP2', 'externe', 'student', NULL, '19-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('20-GP2', 'externe', 'student', NULL, '20-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('21-GP2', 'externe', 'student', NULL, '21-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('22-GP2', 'externe', 'student', NULL, '22-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('23-GP2', 'externe', 'student', NULL, '23-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('24-GP2', 'externe', 'student', NULL, '24-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('25-GP2', 'externe', 'student', NULL, '25-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('26-GP2', 'externe', 'student', NULL, '26-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('27-GP2', 'externe', 'student', NULL, '27-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('28-GP2', 'externe', 'student', NULL, '28-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('29-GP2', 'externe', 'student', NULL, '29-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('30-GP2', 'externe', 'student', NULL, '30-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('31-GP2', 'externe', 'student', NULL, '31-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('32-GP2', 'externe', 'student', NULL, '32-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('33-GP2', 'externe', 'student', NULL, '33-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('34-GP2', 'externe', 'student', NULL, '34-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('35-GP2', 'externe', 'student', NULL, '35-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('36-GP2', 'externe', 'student', NULL, '36-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('37-GP2', 'externe', 'student', NULL, '37-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('38-GP2', 'externe', 'student', NULL, '38-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('39-GP2', 'externe', 'student', NULL, '39-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('40-GP2', 'externe', 'student', NULL, '40-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('41-GP2', 'externe', 'student', NULL, '41-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('42-GP2', 'externe', 'student', NULL, '42-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('43-GP2', 'externe', 'student', NULL, '43-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('44-GP2', 'externe', 'student', NULL, '44-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('45-GP2', 'externe', 'student', NULL, '45-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('46-GP2', 'externe', 'student', NULL, '46-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('47-GP2', 'externe', 'student', NULL, '47-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('48-GP2', 'externe', 'student', NULL, '48-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
  ('49-GP2', 'externe', 'student', NULL, '49-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'boy'),
  ('50-GP2', 'externe', 'student', NULL, '50-GP2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie mécanique (GP)', '2', 'girl'),
--   GE1
  ('1-GE1', 'externe', 'student', NULL, '1-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('2-GE1', 'externe', 'student', NULL, '2-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('3-GE1', 'externe', 'student', NULL, '3-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('4-GE1', 'externe', 'student', NULL, '4-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('5-GE1', 'externe', 'student', NULL, '5-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('6-GE1', 'externe', 'student', NULL, '6-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('7-GE1', 'externe', 'student', NULL, '7-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('8-GE1', 'externe', 'student', NULL, '8-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('9-GE1', 'externe', 'student', NULL, '9-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('10-GE1', 'externe', 'student', NULL, '10-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('11-GE1', 'externe', 'student', NULL, '11-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('12-GE1', 'externe', 'student', NULL, '12-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('13-GE1', 'externe', 'student', NULL, '13-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('14-GE1', 'externe', 'student', NULL, '14-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('15-GE1', 'externe', 'student', NULL, '15-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('16-GE1', 'externe', 'student', NULL, '16-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('17-GE1', 'externe', 'student', NULL, '17-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('18-GE1', 'externe', 'student', NULL, '18-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('19-GE1', 'externe', 'student', NULL, '19-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('20-GE1', 'externe', 'student', NULL, '20-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('21-GE1', 'externe', 'student', NULL, '21-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('22-GE1', 'externe', 'student', NULL, '22-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('23-GE1', 'externe', 'student', NULL, '23-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('24-GE1', 'externe', 'student', NULL, '24-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('25-GE1', 'externe', 'student', NULL, '25-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('26-GE1', 'externe', 'student', NULL, '26-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('27-GE1', 'externe', 'student', NULL, '27-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('28-GE1', 'externe', 'student', NULL, '28-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('29-GE1', 'externe', 'student', NULL, '29-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('30-GE1', 'externe', 'student', NULL, '30-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('31-GE1', 'externe', 'student', NULL, '31-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('32-GE1', 'externe', 'student', NULL, '32-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('33-GE1', 'externe', 'student', NULL, '33-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('34-GE1', 'externe', 'student', NULL, '34-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('35-GE1', 'externe', 'student', NULL, '35-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('36-GE1', 'externe', 'student', NULL, '36-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('37-GE1', 'externe', 'student', NULL, '37-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('38-GE1', 'externe', 'student', NULL, '38-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('39-GE1', 'externe', 'student', NULL, '39-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('40-GE1', 'externe', 'student', NULL, '40-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('41-GE1', 'externe', 'student', NULL, '41-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('42-GE1', 'externe', 'student', NULL, '42-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('43-GE1', 'externe', 'student', NULL, '43-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('44-GE1', 'externe', 'student', NULL, '44-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('45-GE1', 'externe', 'student', NULL, '45-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('46-GE1', 'externe', 'student', NULL, '46-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('47-GE1', 'externe', 'student', NULL, '47-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('48-GE1', 'externe', 'student', NULL, '48-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
  ('49-GE1', 'externe', 'student', NULL, '49-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'boy'),
  ('50-GE1', 'externe', 'student', NULL, '50-GE1@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '1', 'girl'),
--   GE2
  ('1-GE2', 'externe', 'student', NULL, '1-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('2-GE2', 'externe', 'student', NULL, '2-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('3-GE2', 'externe', 'student', NULL, '3-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('4-GE2', 'externe', 'student', NULL, '4-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('5-GE2', 'externe', 'student', NULL, '5-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('6-GE2', 'externe', 'student', NULL, '6-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('7-GE2', 'externe', 'student', NULL, '7-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('8-GE2', 'externe', 'student', NULL, '8-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('9-GE2', 'externe', 'student', NULL, '9-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('10-GE2', 'externe', 'student', NULL, '10-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('11-GE2', 'externe', 'student', NULL, '11-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('12-GE2', 'externe', 'student', NULL, '12-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('13-GE2', 'externe', 'student', NULL, '13-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('14-GE2', 'externe', 'student', NULL, '14-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('15-GE2', 'externe', 'student', NULL, '15-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('16-GE2', 'externe', 'student', NULL, '16-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('17-GE2', 'externe', 'student', NULL, '17-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('18-GE2', 'externe', 'student', NULL, '18-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('19-GE2', 'externe', 'student', NULL, '19-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('20-GE2', 'externe', 'student', NULL, '20-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('21-GE2', 'externe', 'student', NULL, '21-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('22-GE2', 'externe', 'student', NULL, '22-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('23-GE2', 'externe', 'student', NULL, '23-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('24-GE2', 'externe', 'student', NULL, '24-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('25-GE2', 'externe', 'student', NULL, '25-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('26-GE2', 'externe', 'student', NULL, '26-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('27-GE2', 'externe', 'student', NULL, '27-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('28-GE2', 'externe', 'student', NULL, '28-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('29-GE2', 'externe', 'student', NULL, '29-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('30-GE2', 'externe', 'student', NULL, '30-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('31-GE2', 'externe', 'student', NULL, '31-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('32-GE2', 'externe', 'student', NULL, '32-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('33-GE2', 'externe', 'student', NULL, '33-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('34-GE2', 'externe', 'student', NULL, '34-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('35-GE2', 'externe', 'student', NULL, '35-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('36-GE2', 'externe', 'student', NULL, '36-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('37-GE2', 'externe', 'student', NULL, '37-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('38-GE2', 'externe', 'student', NULL, '38-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('39-GE2', 'externe', 'student', NULL, '39-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('40-GE2', 'externe', 'student', NULL, '40-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('41-GE2', 'externe', 'student', NULL, '41-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('42-GE2', 'externe', 'student', NULL, '42-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('43-GE2', 'externe', 'student', NULL, '43-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('44-GE2', 'externe', 'student', NULL, '44-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('45-GE2', 'externe', 'student', NULL, '45-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('46-GE2', 'externe', 'student', NULL, '46-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('47-GE2', 'externe', 'student', NULL, '47-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('48-GE2', 'externe', 'student', NULL, '48-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl'),
  ('49-GE2', 'externe', 'student', NULL, '49-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'boy'),
  ('50-GE2', 'externe', 'student', NULL, '50-GE2@gmail.com', '../images/default_user.png', NULL, NULL, NULL, NULL, 'Génie éléctrique (GE)', '2', 'girl');

